export enum VaultErrors {
  CALLER_IS_NOT_VAULT_OWNER = 'V1',
  ONLY_AMM_VAULT = 'V2',
  NOT_AMM_VAULT = 'V3',
  CALLER_MST_BE_OPERATOR = 'V4',
  CALLER_MST_BE_AMM = 'V5',
  CRATIO_IS_BETWEEN_0_AND_1E6 = 'V6',
  AMOUNT_EXCEED_BALANCE = 'V7',
  SETTLER_IS_INVALID = 'V8',
  AMOUNT_GT_0 = 'V9',
  LONG_SIZE_EXCEED_BALANCE = 'V10',
  PRICE_MUST_BE_FINALIZED = 'V11',
}
