on: ['push', 'pull_request']
name: Test

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update submodules
        id: update
        run: git submodule update --init
      - name: lint
        run: |
          npm install -g npm@latest
          npm install --legacy-peer-deps --frozen-lockfile
          npm run lint:check --parallel
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update submodules
        id: update
        run: git submodule update --init
      - name: test
        run: |
          npm install -g npm@latest
          npm install --legacy-peer-deps --frozen-lockfile
          npm run compile
          npm test
          npm run coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}